#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2021 TTG <prs.ttg+dcs@pm.me>
from importlib import import_module
from re import search, match, findall
from sys import argv
from os import environ
def startswith_lpadded(value: str, key: str, count: int, padding: str = '~'):
	return value.startswith((padding * count) + key)
def get_lpadding(value: str, padding: str = '~'):
	count: int = 0
	for c in value:
		if(c == padding):
			count += 1
		else:
			return count
def dict_value_key(value: object, values: dict):
	for key in values:
		if(values[key] == value):
			return key
	return None
def dict_next(key: object, values: dict):
	f: bool = False
	for k in values:
		if(k == key):
			f = True
		elif(f):
			return k
	return None
def replace_dict(expr: str, replace: str, values: dict):
	for key in values:
		values[key] = values[key].replace(expr, replace)
	return values
def regex_replace_dict(expr: str, replace: str, values: dict):
	for key in values:
		found = search(expr, values[key])
		if(found):
			values[key] = values[key].replace(found.group(), replace)
	return values
def regex_remove_keys_dict(expr: str, values: dict):
	for key in values.copy():
		if(search(expr, values[key])):
			values.pop(key)
	return values
def regex_subdict(expr: str, values: dict):
	ret: dict = {}
	for key in values:
		found = search(expr, values[key])
		if(found):
			ret[key] = values[key]
	return ret
parser_indent: int = 1
command_parser_input: dict = {}
file: str = open(argv[1], 'r').read()
for include in findall("\\@include\\s*.*", file):
	try:
		file = file.replace(include, open(environ['DCS_INCLUDE_PATH'] + '/' + include.replace("@include ", ''), 'r').read())
	except:
		file = file.replace(include, open(include.replace("@include ", ''), 'r').read())
for imp in findall("\\@import\\s*.*", file):
	module = import_module(imp.replace("@import ", '')).__dict__
	globals().update({name: module[name] for name in [name for name in module if not name.startswith('_')]})
lines: list = file.split('\n')
for line in lines:
	command_parser_input[lines.index(line)] = line
command_parser_input = replace_dict('\t', '~', command_parser_input)
command_parser_input = replace_dict(' ' * 4, '~', command_parser_input)
command_parser_input = regex_remove_keys_dict('^#.*$', command_parser_input) 
command_parser_input = regex_remove_keys_dict('^$', command_parser_input)
command_parser_input = regex_remove_keys_dict('^~*$', command_parser_input)
command_labels: dict = regex_subdict('^\\S*:\\s*$', command_parser_input)
command_labels = replace_dict(':', '', command_labels)
variable_map: dict = {}
def parse(message):
	global parser_indent
	message_sub: list = message.split(' ')
	if message_sub[0] in command_labels.values():
		command_ln: int = dict_value_key(message_sub[0], command_labels)
		i: int = list(command_parser_input.keys()).index(command_ln) + 1
		while i < len(command_parser_input):
			line: int = list(command_parser_input.keys())[i]
			if(dict_next(command_ln, command_labels) and (line >= dict_next(command_ln, command_labels) or line > max(command_parser_input.keys()))):
				return
			statement: str = command_parser_input[line]
			statement = statement.replace("%ARGSV", ' '.join(message_sub[1:]))
			arg_vars: list = findall('%ARG_[0-9]', statement)
			for arg in arg_vars:
				if(len(message_sub) > int(arg.split('_')[1]) + 1):
					statement = statement.replace("%ARG_" + str(arg_vars.index(arg)), message_sub[int(arg.split('_')[1]) + 1])
			var_labels: list = findall('%.*=[^=]*', statement)
			if(var_labels):
				for var in var_labels:
					var_sub: list = var.split('=')
					var_sub[0] = var_sub[0].strip()
					for key in variable_map:
						var_sub[1] = var_sub[1].replace('%', '').replace(key, str(variable_map[key]))
					try:
						variable_map[var_sub[0].lstrip('%')] = eval(var_sub[1])
					except:
						variable_map[var_sub[0].lstrip('%')] = var_sub[1]
				i += 1
				continue
			for key in variable_map:
				statement = statement.replace('%' + key, str(variable_map[key]))
			numcond_vars = findall('[0-9]*\\s*[><]\\s*[0-9]*', statement)
			for cond in numcond_vars:
				statement = statement.replace(cond, str(eval(cond)).upper())
			statement_sub: str = statement.split(' ', 1)
			if(get_lpadding(statement) < parser_indent):
				parser_indent = get_lpadding(statement)
			if(startswith_lpadded(statement.upper(), "IF TRUE", parser_indent)):
				parser_indent += 1
				i += 1
				continue
			if(startswith_lpadded(statement.upper(), "CALL", parser_indent)):
				old_indent = parser_indent
				parse(statement_sub[1])
				parser_indent = old_indent
				i += 1
				continue
			if(startswith_lpadded(statement.upper(), "PYVAL", parser_indent)):
				variable_map['return'] = str(eval(statement_sub[1]))
				i += 1
				continue
			if(startswith_lpadded(statement.upper(), "GO", parser_indent)):
				if '+' in statement.upper() or '-' in statement.upper():
					i += int(statement_sub[1])
				else:
					i =  int(statement_sub[1])
				continue
			i += 1
parse("main " + ' '.join(argv[2:]))